spring:
  application:
    name: sample-springdata-service
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/yvfTTvN2ii
    username: yvfTTvN2ii
    password: zxvU9WVftF
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: service-user
      password: 3b99fef5-8b7d-4984-a3d6-124c26914ed7
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
  level:
    org:
      springframework:
        web=DEBUG:
